[10.0][MIG] stock_scanner_shipping
OCA/stock-logistics-barcode pull request #147
Opened 2018-06-12 15:30 UTC by xavierjimenez

Migration of the module **stock_scanner_shipping** to version 10.0

2018-06-13 07:22 UTC, pedrobaeza commented
Runbot warning:
```
2018-06-12 16:12:58,893 180 WARNING openerp_test odoo.addons.base.ir.ir_model: Creating the ir.model.data scanner_scenario_stock in module stock_scanner instead of stock_scanner_shipping.
```

2018-07-08 20:09 UTC, misern2 requested changes
Please rebase and check the requested changes

2018-07-08 20:09 UTC, misern2 commented on stock_scanner_shipping/__manifest__.py
> +        'data/Stock.scenario',
Remove stock.scenario. It is already in stock_scanner module

2018-07-08 20:09 UTC, misern2 commented on stock_scanner_shipping/data/Stock.scenario
> +<?xml version='1.0' encoding='UTF-8'?>
Remove this file.

2019-04-27 13:38 UTC, rousseldenis commented
@xavierjimenez

2022-07-24 12:13 UTC, closed without merging