[13.0] [ADD] stock_picking_product_barcode_report: New module that allows you to select how many labels print for each stock_move_lines
OCA/stock-logistics-barcode pull request #300
Opened 2020-10-07 06:22 UTC by CarlosRoca13

cc @Tecnativa TT25883

This module allows you to select how many labels print for each product of a picking. You can see an example of the wizard and the result in next gif:
![1](https://user-images.githubusercontent.com/35952655/95294769-28e21380-0876-11eb-8202-07f70a47bb02.gif)
As you see in last example the format of the barcode is GS1-128, you can select the default format on the configuration. If you set the camp as blank it will be working with the Odoo formats by default.

Please @sergio-teruel @carlosdauden review this.

2020-10-07 08:32 UTC, lmignon commented
@CarlosRoca13 Thank you for this proposal. I would be nice to be able to select the report format from the print wizard with the default value set to the company's default. ...

2020-10-07 09:40 UTC, CarlosRoca13 commented
@lmignon What you suggest is to select the format of the barcode on the wizard? or select the paperformat?

2020-10-07 11:50 UTC, lmignon commented
> @lmignon What you suggest is to select the format of the barcode on the wizard? or select the paperformat?

I suggest to select theformat of the barcode with default defined by https://github.com/OCA/stock-logistics-barcode/pull/300/files#diff-2a2a39ed07c5da1815a017a4cd2c41e9R21

2020-10-07 12:39 UTC, sergio-teruel requested changes

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/controllers/main.py
> +# -*- coding: utf-8 -*-
You can remove this line...

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/controllers/main.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
Add https...
Be careful with copy - paste

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/controllers/main.py
> +    )
If you do not change any thing you only need  @http.route()

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/controllers/main.py
> +        barcode_format = request.env.company.barcode_default_format
This value must be taken from type definition...

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/controllers/main.py
> +        if barcode_format == "gs1_128":
if type == "gs1_128"

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/controllers/main.py
> +            # image.show()
remove this line

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/controllers/main.py
> +class SVGWitoutTextWriter(SVGWriter):
Please add docstring explaining why yo need this class

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/readme/CONFIGURE.rst
> +#. Go to 'Inventory > Configuration > Operation Types' and active the 'Detailed operations'
This step is not mandatory...

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/readme/USAGE.rst
> +#. Create a new transfer with a product with 'Tracking -> By Lots' and 'Barcode' with a
Does the module work without lots???

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/report/report_label_barcode.xml
> +    <data>
You can remove data tag

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/report/report_label_barcode_template.xml
> +                    <div class="text-center" t-if="doc.product_id.barcode">
Why not only create lines if they have barcodes?? If it you do not need this condition

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/report/report_label_barcode_template.xml
> +                                    t-esc="'(02)' + doc.product_id.barcode.zfill(14) + '(10)' + doc.move_line_id.lot_id.name"
create a variable to store this and you can save a lot code lines.
Also you can store type in a variable...

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
> +        ctx = self.env.context
ctx = self.env.context.copy()

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
> +            raise UserError(_("You may print the labels for just a picking"))
Why??? I want to print por more than one picking...

2020-10-07 12:39 UTC, sergio-teruel commented on stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
> +    picking_id = fields.Many2one("stock.picking")
You can change by picking_ids and we can process more than one picking

2020-10-08 07:30 UTC, CarlosRoca13 commented
@sergio-teruel changes done

2020-10-08 15:50 UTC, sergio-teruel commented
Please add a boolean field to product for avoid print labels...
And add the field into wizard for change format like as @lmignon suggests

2020-10-09 11:02 UTC, CarlosRoca13 commented
@sergio-teruel @lmignon Changes done!

2020-10-09 11:05 UTC, CarlosRoca13 commented
Here you have an example of the result
![captura](https://user-images.githubusercontent.com/35952655/95576024-07c52280-0a30-11eb-9143-aabafc44daac.png)

2020-10-09 11:05 UTC, CarlosRoca13 commented
Here you have an example of the result
![1](https://user-images.githubusercontent.com/35952655/95576062-17446b80-0a30-11eb-93ee-e49e4c55f17e.gif)

2020-10-09 11:08 UTC, pedrobaeza commented
Shouldn't the quantity of labels be defaulted to the quantity done or initial demand in the picking?

2020-10-09 11:13 UTC, CarlosRoca13 commented
That's a possibility, another possibility is like it is right now because we have no info about how the picking will arrive

2020-10-09 11:15 UTC, pedrobaeza commented
OK, I let you decide.

2020-10-15 08:29 UTC, CarlosRoca13 commented
I add one change for avoid a bug on non admin users

2020-10-15 23:41 UTC, manuelcalerosolis commented
@CarlosRoca13 congratulations on this useful module.

I miss a column to represent the lot number in the selection of the number of labels to print.

![image](https://user-images.githubusercontent.com/3088246/96196780-95cd6b80-0f50-11eb-94aa-077312470bce.png)

Is a backport to version 12.0 planned?

Regards

2020-10-16 05:59 UTC, manuelcalerosolis approved these changes
Functional test ok!

2020-10-16 06:40 UTC, CarlosRoca13 commented
I add the Lot Number on the wizard. Actually the backport to 12.0 is not planned, but probably it will be later.

2020-11-25 10:30 UTC, sergio-teruel approved these changes

2020-11-25 10:40 UTC, pedrobaeza commented
/ocabot merge nobump

2020-11-25 10:55 UTC, merged