[MIG] barcodes_generator_abstract: Migration to 14.0
OCA/stock-logistics-barcode pull request #340
Opened 2021-05-19 10:25 UTC by Zar21

Superseeds https://github.com/OCA/stock-logistics-barcode/pull/313

2021-08-09 07:52 UTC, hparfr approved these changes
LGTM

2021-08-17 03:37 UTC, hugho-ad commented
LGTM :+1:

2021-08-17 03:37 UTC, hugho-ad approved these changes

2021-08-17 06:10 UTC, pedrobaeza commented
/ocabot merge nobump

2021-08-17 06:23 UTC, pedrobaeza requested changes

2021-08-17 06:23 UTC, pedrobaeza commented on barcodes_generator_abstract/i18n/es_ES.po
> +# Translation of Odoo Server.
Remove this file

2021-08-17 06:23 UTC, pedrobaeza commented on barcodes_generator_abstract/readme/USAGE.rst
> +----
```suggestion
~~~~
```

2021-08-17 06:34 UTC, pedrobaeza approved these changes

2021-08-17 06:35 UTC, pedrobaeza commented
/ocabot merge nobump

2021-08-17 06:41 UTC, merged

2022-10-04 15:29 UTC, francesco-ooops commented
@legalsylvain could you find a way to get the readme file regenerated? image urls are broken (while they're not in "configuration" file)

thanks"

2022-10-04 15:45 UTC, legalsylvain commented
Image path is bad.you should set "../static/"