14.0 mig product barcode constraint per company
OCA/stock-logistics-barcode pull request #425
Opened 2022-08-04 18:51 UTC by slominchar

2022-08-04 19:35 UTC, legalsylvain approved these changes
Thanks for porting this module. 
Could you add me as maintainer in the manifest ?

2022-08-05 08:15 UTC, robinkeunen approved these changes
A few cosmetic comments, otherwise it looks good 👍

2022-08-05 08:15 UTC, robinkeunen commented on product_barcode_constraint_per_company/readme/DESCRIPTION.rst
> +This contraint was introduced in Odoo V9.0 in [that commit](https://github.com/odoo/odoo/commit/ede1071a09902e6eeb315cf51325a03f3991b3c3), and doesn't fit with some multi companies implementation whe
Still a little typo here : `conStraint`.

2022-08-05 08:15 UTC, robinkeunen commented on product_barcode_constraint_per_company/models/product_product.py
> +                    _("A barcode can only be assigned to one" " product per company !"),
Can you "unslplit" the string here ?

2022-10-01 15:06 UTC, dreispt commented
/ocabot merge nobump

2022-12-20 07:39 UTC, rousseldenis commented
/ocabot migration product_barcode_constraint_per_company

2022-12-20 07:43 UTC, rousseldenis requested changes

2022-12-20 07:43 UTC, rousseldenis commented on product_barcode_constraint_per_company/models/product_product.py
> +                self = self.with_context(prefetch_fields=False)
You are losing context on each loop iteration.

I would have done it before loop.

Moreover, you cannot shadow 'self' name. Use a new variable name like 'self_without_prefetch' or ...

@slominchar Is it wanted to have that context in super() or just for setting _sql_constraints ?

2022-12-22 15:11 UTC, slominchar commented
Good morning @rousseldenis There is a strange issue when he try to run the runboat and fail with a field supostly he create installing purchase module

2023-01-11 12:28 UTC, rousseldenis commented
> Good morning @rousseldenis There is a strange issue when he try to run the runboat and fail with a field supostly he create installing purchase module

Mmmh, could be a problem of dependencies

2023-06-30 08:07 UTC, dreispt commented
/ocabot merge nobump

2023-06-30 08:15 UTC, merged