[16.0][MIG] product_supplierinfo_barcode
OCA/stock-logistics-barcode pull request #446
Opened 2022-10-10 13:58 UTC by tewtawat

Standard Migration

2022-10-10 14:04 UTC, rousseldenis commented
@tewtawat Thanks for this. Could you just add in the description the dependency PR link in order to easy review. Thanks

2022-10-10 14:36 UTC, tewtawat commented
@rousseldenis okay but there're no dependency pr for this module. what should i have to do

2022-10-10 14:39 UTC, rousseldenis commented
> @rousseldenis okay but there're no dependency pr for this module. what should i have to do

Ok, sorry. :sweat_smile:

2022-10-10 14:39 UTC, rousseldenis commented
/ocabot migration product_supplierinfo_barcode

2022-10-10 14:40 UTC, rousseldenis approved these changes
Code review

2022-10-25 10:32 UTC, marylla requested changes
I did a functional review.

I can only set the barcode for a supplier info in its form view when using this menu: purchase > configuration > vendor pricelists.

Unfortunately, it is not possible to add this barcode in product form view in page "purchase" because the tree view for supplier info has a "edit" option to edit it inline and not open a form view. 

I think, we should add the barcode field also in supplier info tree view.

2023-02-23 13:17 UTC, much-sparenberg approved these changes
Weirdly it worked now for me too. :) So everything fine now.

2023-02-23 13:19 UTC, marylla approved these changes
Weirdly it worked now for me too. :) So everything fine now.

2023-05-03 14:33 UTC, enriquemartin commented on product_supplierinfo_barcode/views/product_views.xml
> +    </record>
Why not migrate the view that adds the barcode to the supllierinfo tree in the product form?
Like in version 15: https://github.com/OCA/stock-logistics-barcode/blob/147a3020ebb92fb974f42e115fcc0bbba3b65188/product_supplierinfo_barcode/views/product_views.xml#L18-L27
Tested in local environment and works correctly.

2023-07-11 11:13 UTC, hildickethan-S73 approved these changes

2023-07-11 12:01 UTC, rousseldenis commented
/ocabot rebase

2023-11-13 14:37 UTC, hildickethan-S73 commented
@tewtawat could you rebase the branch? to fix any conflict before merge as it seems like the bot had issues doing that

2024-03-30 09:32 UTC, pedrobaeza requested changes
And check the other existing comment

2024-03-30 09:32 UTC, pedrobaeza commented on product_supplierinfo_barcode/__manifest__.py
> +        "purchase",
Is this still applicable?

2024-03-30 09:32 UTC, pedrobaeza commented on product_supplierinfo_barcode/models/supplierinfo.py
> +            "unique(barcode)",
I think this constraint is too restrictive, as several suppliers may have the same barcode. It should be a combination of unique company, seller and barcode

2024-09-08 12:15 UTC, closed without merging