[14.0][IMP] barcodes_generator_abstract, barcodes_generator_product, barcodes_generator_location: add many sequences
OCA/stock-logistics-barcode pull request #465
Opened 2022-11-18 12:56 UTC by ThiagoMForgeFlow

The barcodes generator abstract module now allows you to create barcode rules based on many sequences, handling the jump between them. The barcodes generator product and barcodes generator location modules now support assigning barcodes from the rule created by the abstract module.

@ForgeFlow

2022-11-18 13:42 UTC, legalsylvain requested changes
Some remarks. I'm not sure about the design proposed but first i'd like to understand the feature. Could you describe a use case for product barcode generation ? (Configuration, user actions, results)

Thanks !

2022-11-18 13:42 UTC, legalsylvain commented on barcodes_generator_abstract/models/barcode_rule.py
> +    ("many sequences", "Base managed by Many Sequences"),
Could you replace space by underscore ?

2022-11-18 13:42 UTC, legalsylvain commented on barcodes_generator_location/models/stock_location.py
> +                    ("generate_type", "=", "many sequences"),
In operator doesnt work ?

2022-11-21 12:22 UTC, ThiagoMForgeFlow commented on barcodes_generator_abstract/models/barcode_rule.py
> +    ("many sequences", "Base managed by Many Sequences"),
Done, thanks

2022-11-21 12:22 UTC, ThiagoMForgeFlow commented on barcodes_generator_location/models/stock_location.py
> +                    ("generate_type", "=", "many sequences"),
Done, thanks

2022-11-21 12:44 UTC, ThiagoMForgeFlow commented
> Some remarks. I'm not sure about the design proposed but first i'd like to understand the feature. Could you describe a use case for product barcode generation ? (Configuration, user actions, results)
> 
> Thanks !

This module is intended for the case in which a company takes ownership of a set of barcodes. But the set is divided into different sequences, and these are to be managed as if it were a single generation rule. For example:

- 2000001000007
- 2000002000006
- 2500001000002
- 2500002000001
- 2500003000000

So now you can create a barcode rule "many_sequences", you select 2 sequences to create, once created you can modify them and put the prefix, the next number and the last number that the sequence allows. In the previous sequences, the following would be modified:

Sequence 1:
-prefix: 20
- next number: 1
-last number: 2
Sequence 2:
-prefix: 25
- next number: 1
-last number: 3

With these settings, the created barcode rule will generate the expected barcodes for the products, managing the jump between the sequences.

2023-04-30 12:11 UTC, closed without merging