[8.0][ADD][product_barcode_generator] Wizard for EAN13 mass assignment
OCA/stock-logistics-barcode pull request #54
Opened 2016-11-22 10:57 UTC by Olageibol

Wizard for EAN13 mass assignment from Product variant tree view. Select items, click on "More..."> Assign Eans. By default, appers the company sequence for EANs

2016-12-01 13:33 UTC, legalsylvain requested changes
Hi. thanks for your contribution.
Some minors comments inline. 
FYI, in V9, there is a new module that supersed this module, using more generical concept. 
https://github.com/OCA/stock-logistics-barcode/tree/9.0/barcodes_generator_product
regards.

2016-12-01 13:33 UTC, legalsylvain commented on product_barcode_generator/wizard/__init__.py
> +#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
Could you set new light header. 
https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3

2016-12-01 13:33 UTC, legalsylvain commented on product_barcode_generator/wizard/__init__.py
> +from . import product_barcode_mass_assignment_wizz
please rename wizz into wizard in your whole PR.

2016-12-01 13:33 UTC, legalsylvain commented on product_barcode_generator/wizard/product_barcode_mass_assignment_wiz_view.xml
> +            <field name="name">Assign Product Barcode</field>
FYI, name key in unnecessary on view record, because it is auto generated.
(not a blocking point)

2016-12-01 13:33 UTC, legalsylvain commented on product_barcode_generator/wizard/product_barcode_mass_assignment_wiz_view.xml
> +        <record model="ir.ui.view" id="product_barcode_mass_assignment_wiz_form">
Following OCA convention, the name should be view_product_barcode_mass_assignment_wizard_form.

2017-02-18 02:39 UTC, lasley commented
Hi @Olageibol - Were you looking to continue forward with this PR?

2022-06-12 12:12 UTC, closed without merging