[16.0][ADD] product_packaging_barcode_constraint_per_company
OCA/stock-logistics-barcode pull request #629
Opened 2024-07-09 05:50 UTC by kevinkhao

2024-07-10 07:22 UTC, rousseldenis requested changes
Code review. Seems great. Some remarks

2024-07-10 07:22 UTC, rousseldenis commented on product_packaging_barcode_constraint_per_company/models/product_product.py
> +        company_ids = self._context.get("search_only_in_pkg_company")
```suggestion
        company_ids = self.env.context.get("search_only_in_pkg_company")
```

2024-07-10 07:22 UTC, rousseldenis commented on product_packaging_barcode_constraint_per_company/tests/test_constraints.py
> +    def setUp(self):
Could you switch to class method ?

2024-08-27 13:38 UTC, kevinkhao commented on product_packaging_barcode_constraint_per_company/tests/test_constraints.py
> +    def setUp(self):
> Could you switch to class method ?

Thank you for feedback. Done

2025-02-23 12:16 UTC, closed without merging