[16.0][MIG] stock_barcodes_picking_batch_revision: Migration to version 16.0
OCA/stock-logistics-barcode pull request #632
Opened 2024-07-29 10:23 UTC by sergio-teruel

cc @Tecnativa TT47634

2024-09-04 12:54 UTC, chienandalu requested changes
Some small changes to improve the readeability of the toggle (to a bigger extent, the former toggle styles had way better ux)


![Peek 04-09-2024 14-52](https://github.com/user-attachments/assets/02749f9c-592f-4802-9d04-51cb84ea274a)

2024-09-04 12:54 UTC, chienandalu commented on stock_barcodes_picking_batch_revision/wizard/stock_barcodes_read_picking_batch_views.xml
> +                    </label>
```suggestion
                    <label for="barcodes_requested_review" class="me-2">
                        Review
                    </label>
                    <field
                        name="barcodes_requested_review"
                        widget="boolean_toggle_big"
                    />
```

2024-09-04 12:54 UTC, chienandalu commented on stock_barcodes_picking_batch_revision/static/src/scss/boolean_toggle_big.scss
> +}
```suggestion
}
.text-white {
    .o_boolean_toggle_big input.form-check-input {
        border-color: white;
    }
}
```

2024-09-05 11:58 UTC, sergio-teruel commented
Changes Done!

2024-09-05 14:11 UTC, carlosdauden approved these changes

2024-09-05 18:46 UTC, pedrobaeza commented
/ocabot migration stock_barcodes_picking_batch_revision

2025-01-09 08:13 UTC, carlosdauden commented
Checks failed

2025-06-22 12:19 UTC, closed without merging