[9.0][IMP] Move from pyBarcode
OCA/stock-logistics-barcode pull request #76
Opened 2017-01-26 23:30 UTC by lasley

* pyBarcode is no longer maintained, switch to viivakoodi fork (https://bitbucket.org/whitie/python-barcode/issues/16/pypi-08-release-request#comment-33978213)

The owner of the fork is active & responsive, thus I recommend we move to that repo. The change is transparent, but the code is slightly better, Travis tested, and will only improve. The other code is basically the opposite of those points. My issues/PRs were handled within an hour:

* https://github.com/kxepal/viivakoodi/issues/6
* https://github.com/kxepal/viivakoodi/pull/5

2017-01-27 11:01 UTC, legalsylvain commented
Hi, @lasley, thanks for your work on pybarcode / viivakoodi.
Except that the name of this new lib is unpronounceable for most people ;-) I see no problem to switch to this new lib.

* indeed last commit on pybarcode was 4 months ago.
* there are not a lot of commits on viivakoodi, but it seems to be more reactive
* Tested on runbot and it works.

I did not analyzed the diff between the two lib, but for me LGTM. :+1: 

@gurneyalex, @OCA/community-maintainers do you have any PoV about that change ? 

kind regards.

2017-01-27 11:01 UTC, legalsylvain approved these changes

2017-01-27 17:47 UTC, lasley commented
FYI I am now a maintainer of the viivakoodi lib, so I can now vouch for its reactivity first hand.

I will add the notes to requirements and Readme in both PRs as you requested in https://github.com/OCA/stock-logistics-barcode/pull/65#issuecomment-275641702

2017-02-01 22:39 UTC, tedsalmon approved these changes
LGTM but the README isn't entirely legible. See review below. 👍

2017-02-01 22:39 UTC, tedsalmon commented on barcodes_generator_abstract/README.rst
> +This module use an extra python library named 'viivakoodi' you should install
`s/use/uses`

2017-02-01 22:39 UTC, tedsalmon commented on barcodes_generator_abstract/README.rst
> +to make barcode generation works properly. 'viivakoodi' is a more active for of
`s/works/work`

`s/is a more active for of/is a more active fork of`

2017-02-02 09:04 UTC, gurneyalex commented
@lasley don't we need a change in the external dependencies in the manifest?

2017-02-02 10:40 UTC, legalsylvain requested changes
+1 for @gurneyalex remark. need to change the name of the lib in the manifest file.

2017-02-02 17:48 UTC, lasley commented
That's not necessary because the manifest file is based on the library import. In this case viivakoodi is a fork of pyBarcodes, both of which provide the `barcode` entrypoint 👍

2017-02-03 07:47 UTC, gurneyalex commented
I just restarted the build which failed because of github errors.

2017-02-03 17:30 UTC, lasley commented
Woot build 🍏 !

2017-02-16 14:37 UTC, legalsylvain approved these changes

2017-02-16 14:37 UTC, legalsylvain commented
Thanks  !

2017-02-16 14:37 UTC, merged