[FIX] Fix v10.0 export scenario script
OCA/stock-logistics-barcode pull request #96
Opened 2017-06-02 10:38 UTC by sylvain-garancher

With the new API migration, some changes were not applied in the script
- The read method now always returns a list (even on a single id)
- The context argument is not at the end, so we need to add the load
    argument when not using named arguments

2017-06-06 08:50 UTC, sylvain-garancher commented
@pedrobaeza @gurneyalex Do you know why the transifex job has been cancelled ?

@lmignon Can review this simple PR ?

2017-06-06 08:51 UTC, pedrobaeza commented
I have restarted it

2017-06-06 08:52 UTC, lmignon commented
@sylvain-garancher I'll review these fixes ASAP...

2017-06-06 09:17 UTC, lmignon approved these changes
:+1: Thank you  @sylvain-garancher ! (Code review and import/export test)

2017-06-06 09:39 UTC, lmignon requested changes

2017-06-06 09:39 UTC, lmignon commented on stock_scanner/scripts/export_scenario.py
> +    int(opts.scenario_id), [], '_classic_read', {'active_test': False})[0]
@sylvain-garancher If teh id is not found  `[0]` raise `IndexError: list index out of range` and `if not scen_read:`will never be called
```python
scen_read = scenario_obj.read(
    int(opts.scenario_id), [], '_classic_read', {'active_test': False})
scen_read = scen_read and scen_read[0]
if not scen_read:
    ....
```

2017-06-06 15:08 UTC, sylvain-garancher commented on stock_scanner/scripts/export_scenario.py
> +    int(opts.scenario_id), [], '_classic_read', {'active_test': False})[0]
Oh, good catch.

2017-06-11 09:29 UTC, sylvain-garancher commented
@lmignon Fixed, thanks.

2017-06-13 08:56 UTC, lmignon commented
@sylvain-garancher Thank you :+1: 
@rousseldenis Can you confirm that this PR works also for you?

2017-06-13 09:34 UTC, alnslang commented
👍

2017-07-19 10:00 UTC, sylvain-garancher commented
@lmignon @rousseldenis Could you review/approve this PR ?

2017-07-19 12:24 UTC, rousseldenis approved these changes
:+1: Code review and tested. Works like a charm!

2017-07-24 07:00 UTC, lmignon approved these changes

2017-07-24 07:02 UTC, merged